// Generated by CoffeeScript 2.7.0
(function() {
  var parse, stringify;

  parse = require('./parse');

  stringify = require('./stringify');

  module.exports.get = function(text) {
    return parse(text, JsonObject.reviver);
  };

  module.exports.getFromFile = async function(path) {
    var fc, fd;
    fd = (await open(path, 'r'));
    fc = fd.createReadStream();
    return get(fc);
  };

  module.exports.toFile = async function(json_obj, path) {
    var fc, fd;
    fd = (await open(path, 'rw'));
    return fc = fd.createWriteStream(stringify(json_obj, {
      space: 2,
      quote: "'"
    }));
  };

}).call(this);
